spring.profiles.active: local
# Prevent the embedded Tomcat from opening a TCP/IP port.
server.port: -1
---
spring.config.activate.on-profile: local
armeria:
  ports:
    - port: 8001
      protocols: HTTP
  internal-services:
    port: 8002

management:
  endpoints:
    web:
      exposure:
        include: env, health, metrics, prometheus
#  server:
#    port: 8002