name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      # The release versions will be verified by 'publish-release.yml'
      - armeria-*
  pull_request:
  merge_group:

concurrency:
  # Cancel the previous builds in the same PR.
  # Allow running concurrently for all non-PR commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  LC_ALL: "en_US.UTF-8"
  BUILD_JDK_VERSION: "19"
  # Used by GitHub CLI
  GH_TOKEN: ${{ github.token }}
  RUN_ID: ${{ github.run_id }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  lint:
    if: github.repository == 'jrhee17/armeria'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - id: setup-build-jdk
        name: Set up JDK ${{ env.BUILD_JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.BUILD_JDK_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run the linters
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=8 --parallel :core:lint
