name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      # The release versions will be verified by 'publish-release.yml'
      - armeria-*
  pull_request:
  merge_group:

concurrency:
  # Cancel the previous builds in the same PR.
  # Allow running concurrently for all non-PR commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  LC_ALL: "en_US.UTF-8"
  BUILD_JDK_VERSION: "19"
  # Used by GitHub CLI
  GH_TOKEN: ${{ github.token }}
  RUN_ID: ${{ github.run_id }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build:
    if: github.repository == 'line/armeria'
    runs-on: ${{ matrix.on }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        on: [ self-hosted, macos-12, windows-latest ]
        java: [ 19 ]
        include:
          - java: 8
            on: self-hosted
          - java: 11
            on: self-hosted
          - java: 17
            on: self-hosted
            leak: true
          - java: 17
            on: self-hosted
            min-java: 11
          - java: 17
            on: self-hosted
            min-java: 17
            coverage: true
          - java: 19
            on: self-hosted
            snapshot: true
            # blockhound makes the build run about 10 minutes slower
            blockhound: true

    name: build-${{ matrix.on }}-jdk-${{ matrix.java }}${{ matrix.min-java && format('-min-java-{0}', matrix.min-java) || '' }}${{ matrix.leak && '-leak' || ''}}${{ matrix.coverage && '-coverage' || ''}}${{ matrix.snapshot && '-snapshot' || ''}}${{ matrix.blockhound && '-blockhound' || ''}}

    steps:
      - name: Set job name
        run: |
          JOB_NAME="build-${{ matrix.on }}-jdk-${{ matrix.java }}${{ matrix.min-java && format('-min-java-{0}', matrix.min-java) || '' }}${{ matrix.leak && '-leak' || ''}}${{ matrix.coverage && '-coverage' || ''}}${{ matrix.snapshot && '-snapshot' || ''}}${{ matrix.blockhound && '-blockhound' || ''}}"
          echo "JOB_NAME=$JOB_NAME" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v3

