name: Upload Gradle build scans to ge.armeria.dev

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  LC_ALL: "en_US.UTF-8"
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  RUN_ID: ${{ github.event.workflow_run.id }}
  COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
  # Used by Octokit
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOWNLOAD_DIR: build-scans/

jobs:
  upload-gradle-cache:
    name: Upload Gradle cache
    if: github.repository == 'jrhee17/armeria'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo the current branch
        run: |
          git status
        shell: bash
