name: update-protobuf

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      target_version:
        description: 'Envoy version to update to'
        required: true
        type: string
      current_version:
        description: 'Current envoy version'
        required: true
        type: string

jobs:
  update-protobuf:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run scripts
        working-directory: ./xds-api/tools/
        run: |
          echo "./upstream-patch.sh --base ${{ inputs.current_version }} --target ${{ inputs.target_version }} --apply"
          ./upstream-patch.sh --base ${{ inputs.current_version }} --target ${{ inputs.target_version }} --apply
          ./update-sha.sh ${{ inputs.target_version }} | tee API_SHAS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-protobuf-to-${{ inputs.target_version }}
          base: main
          author: Meri Kim <dl_armeria@linecorp.com>
          committer: Meri Kim <dl_armeria@linecorp.com>
          signoff: true
          delete-branch: true
          title: '[protobuf] Update xds protobuf definitions to ${{ inputs.target_version }}'
          commit-message: |
            [protobuf] Update xds protobuf definitions to ${{ inputs.target_version }}
          body: |
            This is an automatic PR created by github action workflow:
            - Updated protobuf files
