name: compare-envoy-versions

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      target-version:
        description: "Envoy version we need to update to"
        value: ${{ jobs.compare-envoy-versions.outputs.target-version }}

jobs:
  compare-envoy-versions:
    runs-on: ubuntu-latest
    outputs:
      target_version: ${{ steps.latest-envoy-version.outputs.target-version }}
      current_version: ${{ steps.compare-latest-to-current-version.outputs.current-version }}
      should_update: ${{ steps.compare.outputs.should_update }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest Envoy version
        id: latest-envoy-version
        run: |
          version=$(curl -s https://api.github.com/repos/envoyproxy/envoy/releases/latest | jq -r '.tag_name')
          echo "version=version" >> $GITHUB_OUTPUT
      - name: Read current Envoy version
        id: current-envoy-version
        run: |
          version=$(cat ./xds-api/tools/envoy_release)
          echo "version=version" >> $GITHUB_OUTPUT
      - name: Compare latest to current
        id: compare
        run: |
          if [[ "${{ steps.latest-envoy-version.outputs.version }}" > "${{ steps.current-envoy-version.outputs.version }}" ]]
          then
            echo "should_update=true" >> $GITHUB_OUTPUT
          else
            echo "should_update=false" >> $GITHUB_OUTPUT
          fi
