name: scheduled

permissions:
  contents: read

on:
  workflow_dispatch:
#on:
#  schedule:
#    # every day at 10
#    - cron:  '0 10 * * *'

jobs:
  envoy-versions:
    uses: ./.github/workflows/xds-compare-envoy-versions.yml

  call-update-protobuf:
    permissions:
      contents: write
      pull-requests: write
    needs: envoy-versions
    if: ${{ needs.envoy-versions.outputs.should_update == 'true' }}
    uses: ./.github/workflows/xds-update-protobuf.yml
    with:
      target_version: ${{ needs.envoy-versions.outputs.target_version }}
      current_version: ${{ needs.envoy-versions.outputs.current_version }}
