name: compare-envoy-versions

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      target-version:
        description: "Envoy version we need to update to"
        value: ${{ jobs.compare-envoy-versions.outputs.target-version }}

jobs:
  compare-envoy-versions:
    runs-on: ubuntu-latest
    outputs:
      target-version: ${{ steps.compare-latest-to-current-version.outputs.target-version }}
      current-version: ${{ steps.compare-latest-to-current-version.outputs.current-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest Envoy version
        id: latest-envoy-version
        run: |
          echo 'ENVOY_LATEST<<EOF' >> $GITHUB_ENV
          curl -s https://api.github.com/repos/envoyproxy/envoy/releases/latest | jq -r '.tag_name' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Read current Envoy version
        id: current-envoy-version
        run: |
          echo 'ENVOY_CURRENT<<EOF' >> $GITHUB_ENV
          cat ./xds-api/tools/envoy_release >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Compare latest to current
        id: compare-latest-to-current-version
        run: |
          if [[ "${{ env.ENVOY_LATEST }}" > "${{ env.ENVOY_CURRENT }}" ]]
          then
            echo "target-version=${{ env.ENVOY_LATEST }}" >> $GITHUB_OUTPUT
            echo "current-version=${{ env.ENVOY_CURRENT }}" >> $GITHUB_OUTPUT
          else
            echo "target-version=noop" >> $GITHUB_OUTPUT
            echo "current-version=noop" >> $GITHUB_OUTPUT
          fi
